# Generated by Django 4.2.1 on 2023-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Ввести краткое название на латиннице, которое будет добавляться к основному url для адреса категории', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pages', verbose_name='Изображение'),
        ),
    ]
