# Generated by Django 4.2.1 on 2023-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_category_slug_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category_images', verbose_name='Изображение'),
        ),
    ]
