# Generated by Django 4.2.1 on 2023-06-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_packaging_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packages',
        ),
        migrations.DeleteModel(
            name='Packaging',
        ),
    ]
