# Generated by Django 4.2.1 on 2023-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_product_packages_delete_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, verbose_name='Виды упаковки'),
        ),
    ]
