# Generated by Django 4.2.1 on 2023-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_product_photo_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея фото', 'verbose_name_plural': 'Галерея фото'},
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Фото'),
        ),
    ]
