# Generated by Django 4.2.1 on 2023-06-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_gallery_options_product_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='фасовка')),
            ],
            options={
                'verbose_name': 'Категория фасовки',
                'verbose_name_plural': 'Категории фасовки',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Фото упаковки'},
        ),
        migrations.AddField(
            model_name='product',
            name='weight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_category', to='pages.weightcategory', verbose_name='Весовая категория'),
        ),
    ]
