# Generated by Django 4.2.1 on 2023-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_product_weight_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.FileField(blank=True, upload_to='katalog/', verbose_name='Каталог')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
    ]
